# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\princ\Desktop\DEV\SpaceStationsProject\SpaceStationProject\ui\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(903, 529)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        Form.setFont(font)
        Form.setMouseTracking(False)
        self.UpdateCoordinatesButton = QtWidgets.QPushButton(Form)
        self.UpdateCoordinatesButton.setGeometry(QtCore.QRect(10, 140, 171, 23))
        self.UpdateCoordinatesButton.setStyleSheet("")
        icon = QtGui.QIcon.fromTheme("Dark")
        self.UpdateCoordinatesButton.setIcon(icon)
        self.UpdateCoordinatesButton.setAutoDefault(False)
        self.UpdateCoordinatesButton.setDefault(False)
        self.UpdateCoordinatesButton.setFlat(False)
        self.UpdateCoordinatesButton.setObjectName("UpdateCoordinatesButton")
        self.OpenInGooglMaps = QtWidgets.QPushButton(Form)
        self.OpenInGooglMaps.setGeometry(QtCore.QRect(710, 490, 171, 23))
        self.OpenInGooglMaps.setObjectName("OpenInGooglMaps")
        self.coords_text_label = QtWidgets.QLabel(Form)
        self.coords_text_label.setGeometry(QtCore.QRect(10, 80, 47, 31))
        self.coords_text_label.setObjectName("coords_text_label")
        self.latitudeLabel = QtWidgets.QLabel(Form)
        self.latitudeLabel.setGeometry(QtCore.QRect(100, 70, 91, 31))
        self.latitudeLabel.setObjectName("latitudeLabel")
        self.longitudeLabel = QtWidgets.QLabel(Form)
        self.longitudeLabel.setGeometry(QtCore.QRect(100, 100, 91, 31))
        self.longitudeLabel.setObjectName("longitudeLabel")
        self.StationComboBox = QtWidgets.QComboBox(Form)
        self.StationComboBox.setGeometry(QtCore.QRect(510, 20, 171, 21))
        self.StationComboBox.setStyleSheet("")
        self.StationComboBox.setEditable(False)
        self.StationComboBox.setObjectName("StationComboBox")
        self.StationChooserLabel = QtWidgets.QLabel(Form)
        self.StationChooserLabel.setGeometry(QtCore.QRect(406, 20, 91, 21))
        self.StationChooserLabel.setObjectName("StationChooserLabel")
        self.VisualPassesButton = QtWidgets.QPushButton(Form)
        self.VisualPassesButton.setGeometry(QtCore.QRect(620, 90, 171, 23))
        self.VisualPassesButton.setObjectName("VisualPassesButton")
        self.VisaulPasseslistWidget = QtWidgets.QListWidget(Form)
        self.VisaulPasseslistWidget.setGeometry(QtCore.QRect(616, 130, 256, 192))
        self.VisaulPasseslistWidget.setStyleSheet("color: rgb(255, 0, 0);")
        self.VisaulPasseslistWidget.setObjectName("VisaulPasseslistWidget")
        self.OperatorChooserLabel = QtWidgets.QLabel(Form)
        self.OperatorChooserLabel.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.OperatorChooserLabel.setObjectName("OperatorChooserLabel")
        self.OperatorComboBox = QtWidgets.QComboBox(Form)
        self.OperatorComboBox.setGeometry(QtCore.QRect(100, 20, 171, 21))
        self.OperatorComboBox.setEditable(False)
        self.OperatorComboBox.setObjectName("OperatorComboBox")
        self.OperatorComboBox.addItem("")
        self.durationSpinBox = QtWidgets.QSpinBox(Form)
        self.durationSpinBox.setGeometry(QtCore.QRect(810, 90, 71, 22))
        self.durationSpinBox.setMinimum(1)
        self.durationSpinBox.setMaximum(11)
        self.durationSpinBox.setProperty("value", 1)
        self.durationSpinBox.setObjectName("durationSpinBox")
        self.durationLabel = QtWidgets.QLabel(Form)
        self.durationLabel.setGeometry(QtCore.QRect(810, 60, 91, 16))
        self.durationLabel.setObjectName("durationLabel")
        self.informationText = QtWidgets.QTextBrowser(Form)
        self.informationText.setGeometry(QtCore.QRect(10, 260, 256, 192))
        self.informationText.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.informationText.setObjectName("informationText")
        self.informationLabel = QtWidgets.QLabel(Form)
        self.informationLabel.setGeometry(QtCore.QRect(10, 240, 161, 16))
        self.informationLabel.setObjectName("informationLabel")
        self.informationUpdateButton = QtWidgets.QPushButton(Form)
        self.informationUpdateButton.setGeometry(QtCore.QRect(10, 210, 171, 23))
        self.informationUpdateButton.setObjectName("informationUpdateButton")
        self.VisualPassesTotal = QtWidgets.QLabel(Form)
        self.VisualPassesTotal.setGeometry(QtCore.QRect(620, 340, 211, 16))
        self.VisualPassesTotal.setObjectName("VisualPassesTotal")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DEBUG_BUILD"))
        self.UpdateCoordinatesButton.setWhatsThis(_translate("Form", "<html><head/><body><p>Update station coordinates</p><p><br/></p></body></html>"))
        self.UpdateCoordinatesButton.setText(_translate("Form", "Update coordinates"))
        self.OpenInGooglMaps.setWhatsThis(_translate("Form", "<html><head/><body><p>Open current map location of station</p><p><br/></p></body></html>"))
        self.OpenInGooglMaps.setText(_translate("Form", "Open Map on browser"))
        self.coords_text_label.setText(_translate("Form", "Coords:"))
        self.latitudeLabel.setText(_translate("Form", "None"))
        self.longitudeLabel.setText(_translate("Form", "None"))
        self.StationChooserLabel.setText(_translate("Form", "Choose Satellite"))
        self.VisualPassesButton.setWhatsThis(_translate("Form", "<html><head/><body><p>Open current map location of station</p><p><br/></p></body></html>"))
        self.VisualPassesButton.setText(_translate("Form", "Visual Passes"))
        self.OperatorChooserLabel.setText(_translate("Form", "Choose Operator"))
        self.OperatorComboBox.setItemText(0, _translate("Form", "Russia"))
        self.durationLabel.setText(_translate("Form", "Days(10 max)"))
        self.informationLabel.setText(_translate("Form", "Satellite information"))
        self.informationUpdateButton.setWhatsThis(_translate("Form", "<html><head/><body><p>Open current map location of station</p><p><br/></p></body></html>"))
        self.informationUpdateButton.setText(_translate("Form", "Update satellite info"))
        self.VisualPassesTotal.setText(_translate("Form", "Total Passes:"))
